app:
  name: cat-client

server:
  port: 8010

spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      

core-server.remoteApi: http://127.0.0.1:8012 


retry:
  enable: true
  note: user
  note-match: '{name:"bugcat"}'








